### ISSUE TITLE
🚔 Build output is checked in

### ISSUE THREAD

**Issue by arnemolland** [AllWrite-Bachelor/blog#2]
Build output should _not_ be checked into source control. I see @sebastianberge has added `/build` to .gitignore, but it has already been checked in.

I suggest a similar flow to getting rid of unwanted files:

1. Remove unwanted files as well as the .gitignore mentions of these files. Commit.
2. Add the .gitignore mentions back in. Commit.
3. Clean up the history if wanted, or else the massive `node_modules` directory will forever be in your history.

I also suggest looking at #6 for your build pipeline. A non-optimal solution to the current setup could be creating an Action or CI workflow that builds the blog and pushes it to the `gh-pages` branch, as it could be automated.

Regards,

Antive co.

**Comment by sondregj** [comment]
`node_modules`, forever part of history 😌
